name: Bump Version

on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Release type (patch, minor, major)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Bump version
        id: bump
        run: |
          RELEASE_TYPE="${{ github.event.inputs.release-type }}"

          echo "Bumping version with type: $RELEASE_TYPE"
          NEW_VERSION=$(pnpm version $RELEASE_TYPE --no-git-tag-version | tail -n 1)

          # Clean up possible "v" prefix from pnpm version output
          NEW_VERSION=${NEW_VERSION#v}

          echo "New version: $NEW_VERSION"
          echo "new-version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          VERSION="${{ steps.bump.outputs.new-version }}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json pnpm-lock.yaml
          git commit -m "chore(release): bump version to v$VERSION"
          git tag "v$VERSION"
          git push origin HEAD
          git push origin "v$VERSION"
